
export enum RangeEnum {
  DATERANGE = "DATERANGE",
  TSRANGE = "TSRANGE",
  TSTZRANGE = "TSTZRANGE",
  BIGINTRANGE = "BIGINTRANGE",
  INTEGERRANGE = "INTEGERRANGE",
  NUMERICRANGE = "NUMRANGE",
}

export default RangeEnum

